# Exemplo de configuração. Copie para .streamlit/secrets.toml e edite.
GITHUB_OWNER = "meggavenda-dev"
GITHUB_REPO  = "ponto"
GITHUB_PATH  = "pontos.json"
GITHUB_BRANCH = "main"
GITHUB_TOKEN = "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"
TIMEZONE = "America/Sao_Paulo"
