# Exemplo de configuração. Copie para .streamlit/secrets.toml e edite.
GITHUB_OWNER = "meggavenda-dev"
GITHUB_REPO  = "ponto"
GITHUB_PATH  = "pontos.json"
GITHUB_BRANCH = "main"
GITHUB_TOKEN = "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"
TIMEZONE = "America/Sao_Paulo"
